site_name: 【ポートフォリオサイト制作】コーディングガイド
theme:
  name: "material"
  custom_dir: overrides

  palette:
    primary: cyan
    accent: deep orange

  features:
    - navigation.tabs.sticky

extra_css:
  - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "css/custom.css"

extra:
  analytics:
    provider: google
    property: G-MREMGST625
    feedback:
      title: 役に立ちましたか?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            フィードバックをどうもありがとうございます！
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            フィードバックをどうもありがとうございます！
            改善点がある場合、<a href="mailto:a@kotodute.jp" target="_blank" rel="noopener">メール</a>よりご連絡いただけますと幸いです。

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - footnotes

nav:
  - トップ: index.md
  - よくある質問:
    - 左右中央配置の使い分け: center.md
    - widthとmax-widthの使い分け: width-max-width.md
  - ディレクトリ構成: directory.md
  - ページのtitleとdescription: title-desc.md
  - 困った時のTips:
    - ページ遷移のリンク設定: how-to-link.md
    - 横並びsticky: column-sticky.md
    - タブによる絞り込み実装: category-tab.md
  - 公開手順:
    - 1. チェックリスト: checklist.md
    - 2. ファビコンの設定: favicon.md
    - 3. Github Pagesでの公開のしかた: github-pages.md
  - 役立ちリンク: links.md
